export const AT_POSTS={
    ADD: "ADD_POST",
    DELETE: "DELETE_POST",
    LIST: "LIST_POST",
    LISTALL: "LISTALL_POST"
}
export const AT_COMMENTS={
    ADD: "ADD_COMMENT",
    DELETE: "DELETE_COMMENT",
    LIST: "LIST_COMMENT",
    LISTALL: "LISTALL_COMMENT"
}
export const AT_FRIENDS={
    ADD: "ADD_FRIEND",
    DELETE: "DELETE_FRIEND",
    LIST: "LIST_FIEND",
    LISTALL: "LISTALL_FRIEND"
}